### ISSUE TITLE
Implement Type System for Atoms

### ISSUE THREAD

**Issue by nrdxp** [ekala-project/eka#4]
## Objective
Design and implement a flexible, powerful type system for atoms in eka, inspired by formal type system concepts in languages like Haskell & Rust. Below is the initial draft specification, up for ammendments and refinements.

### Meta-Schema
- Declarative specification (a Rust type) defining schema composition and extension rules
- Specifies constraints on plugin modifications
- Defines allowed operations for each schema element

### Domains (analogous to Haskell's kinds)
- Represent broad categories of atoms, defining both manifest schema elements, as well as meta-schema rules
- Form a hierarchy, each level adding more specific schema elements
- Predefined by eka core or language backends (not extendable by plugins)

Domain Hierarchy:
1. Core: Basic atom properties
2. Depend (extends Core): Dependency management
3. Language (extends Depend): Language-specific concepts
4. Component (extends Language): Concrete, buildable artifacts produced by a language (e.g., packages, libraries, executables)
5. ? (potentially some other domains are warranted)

### Interfaces (analogous to Haskell's type classes)
- Define shared functionality across different domains
- Specify schema extensions and required capabilities
- Can be created and extended by plugins
- Has a static portion (in the definin plugin's manifest) and a language portion (in the defining plugin's code) defining the function APIs that need to be implemented by other plugins that wish to implement the interface

Example Interfaces:
1. Import: For atoms that can be imported in expressions
2. Build: For atoms that can be built
3. Install: For atoms that can be installed
4. NixExpression: For atoms containing Nix expressions

### Traits (analogous to Haskell's types)
- Represent specific types of atoms
- Belong to a domain and implement multiple interfaces
- Define specific schema elements for that atom type
- Can be created and extended by plugins

## Type Definitions Example

```toml
[interface.import]
name = "Import"
schema = "path/to/import.schema.json"

[interface.nixexpr]
name = "NixExpression"
constraints = ["Import"] # user must implement import to implement this interface
schema = "path/to/nixexpr.schema.json"

# eliding other interfaces ...

[type.nix_lib]
name = "NixLib"
domain = "Language"
implements = ["NixExpression"]
schema = "path/to/nixlib.schema.json"

[type.package]
name = "Package"
domain = "Component"
implements = ["Build", "Install"]
schema = "path/to/package.schema.json"

[type.nix_pkg]
name = "NixPkg"
extends = "Package"
domain = "Component"
implements = ["NixExpression"] # also inherits the interfaces of the package type
schema = "path/to/nixpkg.schema.json"
```

## User Manifest Naive Example (NixPkg)

Some of these are probably a bit too verbose, but are kept so purposely here to demonstrate the connection between their interface and type schemas. In reality, we probably want to refine this to be less nested in some areas.

```toml
[atom]
name = "my-awesome-nixpkg"
version = "1.2.0"
description = "An example Nix package atom"
type = "NixPkg"

[meta]
license = "MIT"
maintainers = ["Alice <alice@example.com>", "Bob <bob@example.com>"]

# atom dependencies
[atom.depends.some]
canon = "https://example.com/some.git"
# defaults to the name of the key, this is the name part of the ref used to look up the dependency in the canonical source 
# name = "some"
version = "^1.0" # can be a semver version bound, resolved to a specific compatible version and locked by the resolver

[import.nix]
path = "path/to/atom/root-module"

# fetch legacy nix expressions
[import.nix.fetch.nixpkgs]
url = "https://github.com/nixos/nixpkgs.git"
import = true
args = [{}]

# not sure if we want to declare deps this way or not, but maybe
[build.nix]
build_inputs = ["openssl", "zlib"]

# is there benefit to tracking this kind of information statically?
[build]
build_command = "nix-build"
build_args = ["-A", "my-awesome-tool"]

# just an example, perhaps not necessary?
[install]
install_path = "/usr/local/bin"
```

## Key Design Points
1. Single inheritance for domains & traits
2. Clear domain hierarchy with specific extension rules
3. Interfaces for shared behaviors across domains
4. Meta-schema for declarative composition rules
5. Plugin extensibility for interfaces and traits, not domains

### Typed Collections for Multiple Outputs
We explored allowing atoms to output multiple items via typed collections:

- Pros:
  - Greater flexibility for complex atoms
  - Potential for more comprehensive atoms covering multiple related outputs

- Cons:
  - Risks encouraging overly large, unfocused atoms
  - Potentially undermines the "atomic" nature of atoms
  - Could lead to less modular and reusable components

Decision: We opted against this approach to maintain the focus and simplicity of individual atoms. The current design encourages users to create separate, well-defined atoms for different outputs, promoting modularity and reusability.

### Multi-Domain Traits
We considered allowing traits to belong to multiple domains simultaneously:

- Pros:
  - More flexible representation of complex concepts
  - Easier expression of cross-domain functionalities

- Cons:
  - Increased complexity in type resolution and validation
  - Potential for ambiguity in trait categorization

Decision: We chose a single-domain model for traits to maintain a clear and unambiguous type hierarchy. Cross-domain functionalities are instead handled through interfaces, providing a balance between flexibility and clarity.

## Technical Considerations
- Efficient schema composition and validation algorithms
- Type checking and interface compliance verification
- Version compatibility for domains, interfaces, and traits
- Performance optimization for dynamic schema composition
