### ISSUE TITLE
Static Config

### ISSUE THREAD

**Issue by nrdxp** [ekala-project/eka#9]
## Config?
`Config` is unique, it shall be the only versionable atom domain with no evaluation backend (i.e. static config). All domains above it, starting with `Eval` will expect a backend.

For clarity, the order goes:
1. Atom
```toml
trait = "required" # the atom's unambiguos "type"
[atom]
name    = "required"
version = "required"
```
2. Depend
```toml
# TBF
[deps.<dep>]
version = "required"
# Exactly one value in `vcs` containing an arbitrary vcs name
vcs.git = "url:required" # set to vcs.git.src
```
3. Config
```toml
[<config>...] # where the keyname(s) are defined by the trait that implemented it
```
4. Eval
> TBD
5. ...

## Implementation

Abstracting it to an atom allows including arbitrary static configuration files, including even templates (for later evaluation).

We shall start then with a simple configuration file for `eka` itself, implemented as a a trait: _Eka_. Having this config will also speed development and assist integration testing.

For convenience the user can have a standard config file at ~/.config/eka.toml, or anywhere in repo to configure environment specific values for eka's cli (like an Eos backend url).

In this way, Traits that implement Config must be named after the trait name.

These `<config>.toml`, will mark a general entry where static configuration is expected. It will be inherited by any atom's which live underneath it, providing an expressive global config boundary to be scoped at will, while also provding a clean split where dynamic configuration can reference static config.

Only static configuration is inherited in this way, for sanity and clarity. If you feel your value should propogate, it should probably be static; encouraging a pattern that will keep `eka` efficient in its work.

`<config>.toml` closest to the calling atom will take priority, creating a natural extension mechanism; inheriting for more localized configuration, and terminating at the repo root.

## VCS Config (Draft)

A special VCS trait (vcs.toml) _can_ exist at the project top-level, but nowhere else. The config value `[atom.repo]<vcs>` can only be defined here. This is the value that atom's will have to either set directly to declare this atom as a dependency, or an html `<meta>` may at some point specify ([#8](#8)) (and therefore redirect to).

 This is a feature, allowing unambiguous information required to make reliable decisions in the resolver layer to be expressed in an expected location, and also weeding out non-sensical or perhaps malicious scenarios during resolution. Since this information is inhereited by design, it also ensures every atom living in this repo cannot misrepresent its canonical home.
 
 If a `vcs.toml` does not exist, then a repository can still make use of `eka`. But atom's contained within will not be exposed (no external atom can spec it as a dependency), and can only depend on each other by relative path. However, they can stll have arbitrary remote dependencies.

 a `vcs.toml` doubles as a convenient location to express information that is usually implicit to your vcs (e.g, a repo local git conf, the installed git hooks, etc). Everything in the file beside `[atom]` will be expected to be a path or remote reference to a file.
 
A backend (Nix) can take this and pull the sources, symlinking them into the repo relative to the canonical vcs local repo configuration directory (e.g. `.git`) during a simple resolution phase which commits them to:  `refs/eka/vcs-0.7.0` (in the example below)

This ensures the configuration doesn't drift, even if you are on a different machine, or a remote goes down.
 
 #### Draft VCS Schema
 ```toml
 [atom]
 name = "my-repo"
 version = "0.7.0"
 repo.git = "https://github.com/
 
 # linked to `.git/config` based on `repo.<vcs>` above
 [config] 
 path = /abs/or/rel/git-config-snippet
 
  # linked to `.git/hooks/cool`
 [hooks.cool]
 url = https://some.io/cool/hook
 ```
